alias config="/usr/bin/git --git-dir=$HOME/Projects/dotfiles/ --work-tree=$HOME"
alias s="sudo"
alias c="clear"
alias v="nvim"
alias vim="nvim"
alias gc="git clone"
alias ga="git add"
alias gpl="git pull"
alias gs="git status"
alias gph="git push"
alias gcm="git commit"
alias ka="killall"
alias rf="rm -rf"
alias xup="xrdb -load ~/.config/X11/xresources"
alias ls="ls -a --group-directories-first --color=auto"
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
