alias config="/usr/bin/git --git-dir=$HOME/Projects/dotfiles/ --work-tree=$HOME"
alias s="sudo"
alias c="clear"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias gc="git clone"
alias ga="git add"
alias gpl="git pull"
alias gs="git status"
alias gph="git push"
alias gcm="git commit -m"
alias gch="git checkout"
alias gd="git diff"
alias gbr="git branch"
alias gl="git log"
alias ka="killall"
alias rf="rm -rf"
alias xup="xrdb -load ~/.config/X11/xresources"
alias ls="ls -a --group-directories-first --color=auto"
