#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then # check if external monitor exists
    xrandr --output LVDS1 --mode 1366x768 --rotate normal --primary --output HDMI1 --mode 1920x1080 --rotate normal --left-of LVDS1 &
    bspc monitor HDMI1 -d 1 2 3 4 5
    bspc monitor LVDS1 -d 6 7 8 9 10
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width	2
bspc config window_gap		12
bspc config split_ratio		0.52
