#!/bin/sh

focused=$(xrdb ~/.config/X11/xresources -query all | grep foreground | cut -f2)
normal=$(xrdb ~/.config/X11/xresources -query all | grep color8 | cut -f2)

bspc monitor -d TERM WEB CODE FILES MEDIA EXTRA

bspc config focused_border_color	"$focused"
bspc config normal_border_color		"$normal"
bspc config border_width		    2
bspc config window_gap 			    5
bspc config focus_follows_pointer	false
bspc config top_padding             38
bspc config split_ratio			    0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		    false
bspc config single_monocle		    true

bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a mpv desktop='^5' state=fullscreen follow=on
bspc rule -a feh state=fullscreen follow=on

$HOME/.config/polybar/launch.sh &
./.fehbg &
run_dunst &
floating_noborder &
picom &
syncthing &
